/*
1. PAGE NAME
   Profile Dummy Data

2. PURPOSE
   Supplies realistic local multilingual profile data for UI development.

3. DESCRIPTION
   Contains no networking, database, authentication, or persistence logic.

4. UI SECTIONS
   Profile identity and language preference.

5. NAVIGATION FLOW
   Dummy data → MockProfileDataSource → ProfilePage.

6. DYNAMIC COMPONENTS
   ProfileFeatureModel.

7. FUTURE BACKEND INTEGRATION
   Replace this local source with the application's profile data source when
   account/profile persistence is implemented.

8. TECHNOLOGIES USED
   Pure Dart.

9. REQUIRED DATA MODELS
   ProfileFeatureModel.

10. FUTURE API ENDPOINTS
    Not specified by the supplied project documentation.

11. DATABASE COLLECTIONS/TABLES
    Not specified by the supplied project documentation.

12. REQUIRED ASSETS
    None.

13. REQUIRED ICONS
    None.

14. THEME COLORS
    Not applicable.

15. ANIMATIONS
    None.

16. ACCESSIBILITY
    Presentation responsibility.

17. EDGE CASES
    The model contains multilingual text to exercise text layout.

18. VALIDATION RULES
    None.

19. ERROR HANDLING
    None.

20. LOADING STATE
    Generated by the controller.

21. EMPTY STATE
    Generated by the controller.

22. OFFLINE BEHAVIOUR
    Local data remains available without network access.

23. SECURITY CONSIDERATIONS
    All values are fictional demonstration data.

24. PERFORMANCE OPTIMIZATIONS
    Static const data.

25. WIDGET TREE OVERVIEW
    Not applicable.

26. COMPLETE TESTING CHECKLIST
    Verify multilingual text and long-value rendering.
*/

import '../models/profile_feature_model.dart';

const ProfileFeatureModel profileDummyData = ProfileFeatureModel(
  displayName: 'Arjun Kumar',
  email: 'arjun.kumar@example.com',
  preferredLanguage: 'தமிழ் (Tamil)',
  targetLanguage: 'English',
  statusLabel: 'Ready for multilingual conversations',
  initials: 'AK',
);
